buildscript {
	repositories {
		maven { url 'https://maven.fabricmc.net/' }
		mavenCentral()
	}
	dependencies {
		classpath "net.fabricmc:fabric-loom:${loom_version}"
	}
}

apply plugin: 'fabric-loom'
apply plugin: 'maven-publish'

group             = project.maven_group
version           = project.mod_version
archivesBaseName  = project.archives_base_name

base {
	archivesName = project.archives_base_name
}

dependencies {
	// Minecraft itself
	minecraft     "com.mojang:minecraft:${minecraft_version}"
	// Yarn mappings
	mappings      "net.fabricmc:yarn:${yarn_mappings}:v2"
	// Fabric loader
	modImplementation "net.fabricmc:fabric-loader:${loader_version}"
	// Fabric API (highly recommended) (optional)
	// modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
	inputs.property "version",            project.version
	inputs.property "minecraft_version",  project.minecraft_version
	inputs.property "loader_version",     project.loader_version
	inputs.property "fabric_version",     project.fabric_version

	filesMatching("fabric.mod.json") {
		expand(
				"version"          : project.version,
				"minecraft_version": project.minecraft_version,
				"loader_version"   : project.loader_version,
				"fabric_version"   : project.fabric_version
		)
	}
}
java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	withSourcesJar()
}
tasks.withType(JavaCompile).configureEach {
	options.release = 21
}

jar {
	from("LICENSE") {
		rename { "${it}_${archivesBaseName}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifactId = archivesBaseName
		}
	}
	// repositories {
	//     maven {
	//         name = "Modrinth"
	//         url  = uri("https://api.modrinth.com/v2/projects")
	//         credentials { /*...*/ }
	//     }
	// }
}
